export const NAVIGATION_TO_LOADING_SCREEN = 'LoadingScreen';
export const NAVIGATION_TO_SIGNIN_SCREEN = 'SigninScreen';
export const NAVIGATION_TO_SIGNUP_SCREEN = 'SignupScreen';
export const NAVIGATION_TO_HOME_SCREEN = 'HomeScreen';
export const NAVIGATION_TO_FEEDS_SCREEN = 'FeedsScreen';
export const NAVIGATION_TO_FORYOU_SCREEN = 'ForYouScreen';
export const NAVIGATION_TO_FOLLOWING_SCREEN = 'FollowingScreen';
export const NAVIGATION_TO_RECENT_SCREEN = 'RecentScreen';
export const NAVIGATION_TO_SEARCH_SCREEN = 'SearchScreen';
export const NAVIGATION_TO_UPLOAD_SCREEN = 'UploadScreen';
export const NAVIGATION_TO_NOTIFICATION_SCREEN = 'NotificationScreen';
export const NAVIGATION_TO_USER_PROFILE_SCREEN = 'UserProfileScreen';
export const NAVIGATION_TO_DETAIL_SCREEN = 'DetailScreen';

/* 
    login
*/
export const NAVIGATION_TO_LOGGININ = 'NAVIGATION_TO_LOGGININ';
export const NAVIGATION_TO_REGISTER = 'NAVIGATION_TO_REGISTER';
export const NAVIGATION_TO_LOGIN_NAVIGATOR = 'NAVIGATION_TO_LOGIN_NAVIGATOR';
export const NAVIGATION_TO_PERSONAL_INFO = 'NAVIGATION_TO_PERSONAL_INFO';
export const NAVIGATION_TO_PHONE_VERIFY = 'NAVIGATION_TO_PHONE_VERIFY';

/* 
    upload
*/
export const NAVIGATION_TO_UPLOAD_VIDEO = 'NAVIGATION_TO_UPLOAD_VIDEO';
export const NAVIGATION_TO_UPLOAD_DUEL = 'NAVIGATION_TO_UPLOAD_DUEL';
export const NAVIGATION_TO_UPLOAD_CAPTION = 'NAVIGATION_TO_UPLOAD_CAPTION';